# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(211, 202)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serverSelectComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.serverSelectComboBox.setGeometry(QtCore.QRect(30, 30, 151, 21))
        self.serverSelectComboBox.setObjectName("serverSelectComboBox")
        self.makeBackupButton = QtWidgets.QPushButton(self.centralwidget)
        self.makeBackupButton.setGeometry(QtCore.QRect(30, 60, 151, 21))
        self.makeBackupButton.setObjectName("makeBackupButton")
        self.overwriteCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.overwriteCheckBox.setGeometry(QtCore.QRect(30, 90, 151, 21))
        self.overwriteCheckBox.setObjectName("overwriteCheckBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label.setObjectName("label")
        self.folderPathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.folderPathLineEdit.setGeometry(QtCore.QRect(30, 130, 151, 16))
        self.folderPathLineEdit.setText("")
        self.folderPathLineEdit.setReadOnly(True)
        self.folderPathLineEdit.setObjectName("folderPathLineEdit")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(60, 150, 91, 21))
        self.browseButton.setObjectName("browseButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.addServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addServerButton.setGeometry(QtCore.QRect(6, 30, 21, 21))
        self.addServerButton.setObjectName("addServerButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 211, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.makeBackupButton.setText(_translate("MainWindow", "Make Backup"))
        self.overwriteCheckBox.setText(_translate("MainWindow", "Overwrite previous save"))
        self.label.setText(_translate("MainWindow", "Backups Folder:"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Servers:"))
        self.addServerButton.setText(_translate("MainWindow", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
